name = "quantum-skies"
author = "jmoiron"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f33b95213338fd52b4b32ceb112aceea15b44a407973e37062e6d4e1d4775d3"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
