name = "quantum-skies"
author = "jmoiron"
version = "0.9.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6802158ebeb831e8eba1af4c489b0b90b957dab36170da11bf5260cca11b4c53"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
