name = "quantum-skies"
author = "jmoiron"
version = "0.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57b8e0cb20af60753dc7bb9ccda58e40aa9c0d1393b1cb104122c010ee7b7891"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
